### ISSUE TITLE
Search based on temporal extent not working?

### ISSUE THREAD

**Issue by m-mohr** [microsoft/planetary-computer-apis#100]
**Describe the bug**
I'm requesting `https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a/items?limit=12&datetime=2022-04-30T00:00:00Z/2022-05-30T00:00:00Z&sortby=-properties.datetime` with a temporal extent covering mostly May 2022, but I'm getting data from June as result (the first Item right now has `2022-06-05T01:27:21.024000Z` as datetime)

**To reproduce**
See above.

**Expected behavior**
I'd expect that only data up until 2022-05-30T00:00:00Z is returned.

**Comment by mmcfarland** [comment]
Thanks for this report @m-mohr. I can confirm that search parameters on the `/item` endpoint are not currently working as expected. Note for you or others trying to use this `GET` syntax while we investigate a fix, that the `GET /search` endpoint is working as expected, e.g.:

https://planetarycomputer.microsoft.com/api/stac/v1/search?collections=sentinel-2-l2a&datetime=2022-04-30T00:00:00Z/2022-05-30T00:00:00Z&limit=12
