### ISSUE TITLE
Request: Add sensor viewing angles to Sentinel-2 scene properties from STAC

### ISSUE THREAD

**Issue by lukasValentin** [microsoft/planetary-computer-apis#103]
We are currently using pystac-client to retrieve Sentinel-2 metadata (L2A) from Planetary computer and its STAC. While we found the mean solar azimuth angle (`s2:mean_solar_azimuth`) and mean solar zenith angle (`s2:mean_solar_zenith`) in the scene `properties`, the data about mean sensor azimuth and mean sensor zenith angle seems to be missing.

In our project, however, we'd require scene-wide angular information to run radiative transfer model simulations. In addition, we think that providing the entire angular data might be very helpful also for other users.

So, the proposal is to add the sensor azimuth and sensor zenith angle data as further entries to the scene properties. We are aware that the STAC specifications are undergoing, therefore, this feature request might be even placed wrong here, but we think it is an important addition to the current catalog.

We are looking forward to your answer. Thanks in advance.

**Comment by TomAugspurger** [comment]
Thanks for the feedback @lukasValentin.  The Planetary Computer uses https://github.com/stactools-packages/sentinel2 to generate the STAC items from the files and XML metadata. Would you mind re-submitting this issue over there to get feedback from others using that library to generate sentinel2 STAC items?

**Comment by lukasValentin** [comment]
Thanks @TomAugspurger for the prompt answer; I re-submitted the issue to stactools (https://github.com/stactools-packages/sentinel2/issues/50)

**Comment by TomAugspurger** [comment]
Thanks. We'll close this then.
