### ISSUE TITLE
describedBy link on collections is incorrect

### ISSUE THREAD

**Issue by lossyrob** [microsoft/planetary-computer-apis#13]
**Describe the bug**
The `describedBy` link is incorrect. This is due to an inappropriate use of urljoin [in this code](https://github.com/microsoft/planetary-computer-apis/blob/main/pcstac/pcstac/client.py#L58)

**To reproduce**
Notice the collection link with "describedBy" does not contain the "dataset" component of the path.

**Comment by mmcfarland** [comment]
Fixed via https://github.com/microsoft/planetary-computer-apis/pull/33/commits/1ae530727fc0940d40b7050bd7c5fc379a4e1eae
