### ISSUE TITLE
serving tiles in react frontend

### ISSUE THREAD

**Issue by aghand0ur** [microsoft/planetary-computer-apis#179]
Hello,

I am wondering if it is possible to use Planetary API as a WSM endpoint to serve sentinel & landsat tile in a front page.

Ali

**Comment by aghand0ur** [comment]
WMTS seems to be supported.
any example how to use it?

**Comment by TomAugspurger** [comment]
> WMTS seems to be supported.

I'm not sure this is correct. I think our tiler only serves z/y/x tiles associated with a specific STAC search (show at https://planetarycomputer.microsoft.com/docs/quickstarts/using-the-data-api/#Mosaic-multiple-items) or individual STAC items.

But if you do get an example working, please do share!

**Comment by aghand0ur** [comment]
thank you @TomAugspurger
